### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-design-ws#18]
index.html

**Comment by emartinez-usgs** [comment]
- Output will have "metadata" and "data" keys at the top level.
  - "metadata" will have "status", "date", "url", and "parameters" keys.
  - "data" will have "data" and "metadata" keys
    - "data.metadata" will have "pgaFloor" ... "ssPercentile" keys
    - "data.data" will have "designCategory" ... "tl" keys
- Update example output to match

- Typo in max direction descriptions "ot" should be "to"
- Incorrectly referencing "0.2 second)" on "s1Percentile" description

- Comment out some fields because they are not going to be implemented yet. Do not delete this, because eventually we will implement:
  - designCategory
  - sdSpectrum
  - smSpectrum
  - tl

- Add some introductory text to index.html top-level page. "EndPoint" should be "Available End Points" and should list "design.json" as one (and currently the only) such available end point.

- Provide an example [working] request link on the design.html page that will produce results. Ideally, the example results embedded inline.

 - Risk categories are roman numerals "I", "II", "III" or "IV"
- Site classes are text strings, "A", "B", "B (measured)", "B (unmeasured", "C", "D (default)", "D (determined)", "E"

**Comment by emartinez-usgs** [comment]
- ssuh --> ssrt (with descriptions from document)
- s1uh --> s1rt (with descriptions from document)
- Missing s1dFloor description
- Should use subscripts for MCR<sub>R</sub> MCE<sub>G</sub>
