### ISSUE TITLE
Get 2002 Data for ASCE7-05

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-design-ws#225]
- Talk to Eric
- Update data loaders
  - Data is only added to probabilistic data

**Comment by emartinez-usgs** [comment]
RND files available on FTP. Convert RND files to CSV and store on FTP for this tool.

Exiting files: ftp://hazards.cr.usgs.gov/web/earthquake-legacy-usdesign/
 - Alaska: 1997-AK-MCE-R1a.rnd
 - Hawaii: 1998-HI-MCE-R1a.rnd
 - PRVI: 2003-PRVI-MCE-R1a.rnd
 - Conterminous US
   - PACNW: 2003-PacNW-MCE-R1a.rnd
   - CANV: 2003-CANV-MCE-R1a.rnd
   - CEUS: 2003-CEUS-MCE-R1a.rnd
  - SLC: 2003-SLC-MCE-Ra.rnd
   - Otherwise: 2003-US-MCE-R1a.rnd

Bounds for COUS sub-regions...
```
// CANV
lon >= -125 && lon <= -115 && lat <= 42 && lat >= 32
 
// PACNW
lon >= -125 && lon <= -123 && lat <= 49 && lat >= 41

// SLC
lon >= -112 && lon <= -110 && lat <= 45 && lat >= 40

// CEUS
lon >= -92 && lon <= -88 && lat <= 38 && lat >= 35

// If not one of the above, use default "2003-US-MCE-R1a.rnd"
```

**Comment by jdbrown-USGS** [comment]
@emartinez-usgs:

- .rnd files only include 2 data values per lat/lon.

- Based on this apparently related data file, It appears the files do not include PGA, and swap the order of SS and S1 values as compared to previously used data files.  Also, SS values appear to be smaller than S1 values in general, so the binary files seem to support this hypothesis...
ftp://hazards.cr.usgs.gov/web/earthquake-designmaps/datasets/geo/1997-AK-MCE-R1a.txt

- Labeled columns as they appear to be created
- Added pga column with value of -1 to end of file (which seems like an invalid value, but correct this assumption if wrong).

The probabilistic service should probably be updated to omit pga values at least for this dataset, or possibly based on the -1 placeholder value.  Thoughts?

**Comment by jmfee-usgs** [comment]
@emartinez-usgs : this may be the first data set with overlapping regions, is the intent to make it use the smallest matching region first?

**Comment by emartinez-usgs** [comment]
Yes - order by region size, smallest first. But that is not part of this ticket I think.
