### ISSUE TITLE
Update data loader to be incremental

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-design-ws#235]
- Only data that has not been loaded is loaded

**Comment by emartinez-usgs** [comment]
Installer script for each gridded dataset (prob/det/rc)...

- Would you like to load the schema?
  - If Yes, drop/reload schema, no need to ask other questions; answer is necessarily yes (since DB is otherwise empty)

- Would you like to load the reference data?
  - If Yes, for each region (in regions file), check if documents/regions already exist in database...
    - If Yes, notify user documents/region already exist, ask if user would like to refresh region.
      - If yes, drop region and corresponding documents/data and reload region/documents.
    - If not, load region.

- Would you like to load the data?
  - If Yes, for each dataset, check if data already exists for this dataset...
    - If yes, notify data exists and ask if user would like to reload the data.
      - If yes, drop and reload data.
      - If no, skip
    - If not, ask if user would like to load the data
      - If yes, load data
      - If no, skip

Installer script for each dataset should accept the following command line flags
  - `--silent` Do not prompt user, assume answer *yes* to all questions effectively reloading all the data.
  - `--missing` Do not prompt user. Do not drop/reload schema. Do not drop existing regions/documents. DO add missing regions/documents. Do load missing data.

Note: When loading data into the `data` table, it is fastest to drop the index on the data table, then load the data, then re-add the index. If loading multiple datasets, only drop the index once, then add the index again after all data has been loaded.

**Comment by emartinez-usgs** [comment]
- The data.region_id has an index on it in deterministic, but not in probabilistic or risk-coefficient. It should probably be consistent across all schemas.
- The data.id column in probabilistic is no longer the primary key, why is that? This should be the same across all schemas.
